services:
  - type: web
    name: blood-donation-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 5000
      - key: MYSQL_HOST
        sync: false
      - key: MYSQL_PORT
        value: 3306
      - key: MYSQL_USER
        sync: false
      - key: MYSQL_PASSWORD
        sync: false
      - key: MYSQL_DATABASE
        value: blood_donation_system
      - key: ADMIN_NAME
        value: Blood Bridge Admin
      - key: ADMIN_USERNAME
        value: admin
      - key: ADMIN_PASSWORD
        value: admin123
